# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.0.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: scripts/infoplist.sh
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 6 (12.2) [" || true
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Install gems
          command: bundle install --path circle_vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - circle_vendor/bundle
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods
      - run:
          name: Map GoogleService-Info.plist
          command: |
            [ ! -z "$GOOGLE_SERVICE_INFO_PLIST_PRODUCTION" ] 
            echo $GOOGLE_SERVICE_INFO_PLIST_PRODUCTION | base64 --decode -o Resources/Plists/GoogleService-Info.plist
      - run: bundle exec fastlane unit_tests
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  build-development:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run: scripts/infoplist.sh
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Install gems
          command: bundle install --path circle_vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - circle_vendor/bundle
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods
      - add_ssh_keys: 
          fingerprints:
            - "25:d8:d7:7b:20:a3:1a:62:96:72:34:10:5d:2a:92:9d"
            - "fa:f9:91:c4:51:b6:ab:85:bb:ca:bf:d2:b6:70:ca:db"
      - run:
          name: Map GoogleService-Info.plist
          command: |
            [ ! -z "$GOOGLE_SERVICE_INFO_PLIST_PRODUCTION" ] 
            echo $GOOGLE_SERVICE_INFO_PLIST_PRODUCTION | base64 --decode -o Resources/Plists/GoogleService-Info.plist
      - run:
          name: Build QA
          command: bundle exec fastlane qa

  build-production:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run: scripts/infoplist.sh
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Install gems
          command: bundle install --path circle_vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - circle_vendor/bundle
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods
      - add_ssh_keys: 
            fingerprints:
              - "25:d8:d7:7b:20:a3:1a:62:96:72:34:10:5d:2a:92:9d"
              - "fa:f9:91:c4:51:b6:ab:85:bb:ca:bf:d2:b6:70:ca:db"
      - run:
          name: Map GoogleService-Info.plist
          command: |
            [ ! -z "$GOOGLE_SERVICE_INFO_PLIST_PRODUCTION" ] 
            echo $GOOGLE_SERVICE_INFO_PLIST_PRODUCTION | base64 --decode -o Resources/Plists/GoogleService-Info.plist
      - run:
          name: Build Production
          command: bundle exec fastlane prod

  refresh-signing:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run: scripts/infoplist.sh
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Install gems
          command: bundle install --path circle_vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - circle_vendor/bundle
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods
      - add_ssh_keys: 
            fingerprints:
              - "25:d8:d7:7b:20:a3:1a:62:96:72:34:10:5d:2a:92:9d"
              - "fa:f9:91:c4:51:b6:ab:85:bb:ca:bf:d2:b6:70:ca:db"
      - run:
          name: Refresh signing
          command: bundle exec fastlane refresh_signing

workflows:
  version: 2
  test_release:
    jobs:
      - build-and-test:
          filters:
            branches: 
              ignore:
                - develop
                - master
                - /release.*/
      - build-development:
          filters:
            branches:
              only: 
                - develop
      - build-production:
          filters:
            branches:
              only: 
                - /release.*/

